### ISSUE TITLE
vid/pid for chip not in the list yet

### ISSUE THREAD

**Issue by bkerin** [per1234/zzInoVIDPID#1]
This chip doesn't have an entry in the list:  CY7C65213

The vid/pid for this chip are: {vendor => '04b4', product => '0003'} ];   # CY7C65213 chip

It's probably at least somewhat common now as it's on sparkfun product: BOB-13830

**Comment by per1234** [comment]
I have added CY7C65213 and done a release of the updated package. Thanks!
